== jaguar-forge-addon
:idprefix: id_ 

The jaguar-forge-addon enables developers to generate Java projects that use the Jaguar Framework (http://www.powerlogic.org/).

This addon provides *standalone* functionality, and it can be re-used in other addons.

=== Dependencies:
=== Depends on
[options="header"]
|===
|Addon    |Exported |Optional
|cdi      |no       |no
|maven    |no       |no
|projects |no       |no
|===

== Setup

This Addon requires the following installation steps.

=== Add configuration to pom.xml 

To use this addon, you must add it as a dependency in the *pom.xml* of your `forge-addon` classified artifact:
(Make sure the dependency is put all the way to the left, and uses 3 spaces for indentation of GAV)
[source,xml]
----
<dependency>
   <groupId>org.cubekode.jaguar.forge.addon</groupId>
   <artifactId>jaguar-forge-addon</artifactId>
   <classifier>forge-addon</classifier>
   <version>${version}</version>
</dependency>
----

== Features
* Generate Jaguar project, based on INI Zip Templates.

== Usage

=== Prerequsites

JBoss Tools with Forge 2.4.1, or JBoss Forge-CLI 2.4.1.

=== Install the addon:

Assuming JBoss Tools with Forge, or Forge-CLI is installed:

*(JBT)*

Ctrl+4. Run the "Install the addon from Git" command, using these coordinates: https://github.com/adolfojunior/jaguar-forge-addon.git

*(Forge-CLI)*

----
$ addon-install-from-git --url https://github.com/adolfojunior/jaguar-forge-addon.git
----

=== Create a new project

*(JBT)*

Ctrl+4. Run the "Project: New" command. Create a new jaguar web application, named 'jaguarapp', type "Jaguar Project".

*(Forge-CLI)*

----
$ project-new --named jaguarapp --type jaguar --topLevelPackage org.jaguar.sampleapp
----

The addon will request the INI Project type as below:

[0] ( ) jcompany_ini_extension
[1] ( ) jcompany_ini_facelets_bridge
[2] ( ) jcompany_ini_facelets_cdi
[3] ( ) jcompany_ini_facelets_cdi_bridge
[4] ( ) jcompany_ini_facelets_cdi_bridge_simple
[5] ( ) jcompany_ini_facelets_cdi_jboss
[6] ( ) jcompany_ini_facelets_cdi_modulo
[7] ( ) jcompany_ini_facelets_cdi_modulo_simple
[8] ( ) jcompany_ini_facelets_cdi_prime
[9] ( ) jcompany_ini_facelets_cdi_rich
[10] ( ) jcompany_ini_facelets_cdi_simple
[11] ( ) jcompany_ini_facelets_modulo_cdi
[12] ( ) jcompany_ini_facelets_modulo_cdi_simple
[13] ( ) jcompany_ini_jaguar_archetype
[14] ( ) jcompany_ini_modulo_negocio
[15] ( ) jcompany_ini_modulo_servico

After chose the INI type, the addon will list the available Jaguar versions in Powerlogic Repository. Choose wisely!

== Future Commands

Scaffold is comming soon!
